apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-trip-app
  namespace: production
  labels:
    app: next-trip
    environment: production
    version: v1
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: next-trip
      environment: production
  template:
    metadata:
      labels:
        app: next-trip
        environment: production
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/api/metrics"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - next-trip
              topologyKey: kubernetes.io/hostname
      containers:
      - name: next-trip
        image: ghcr.io/charwinvanryckdegroot/next-trip-anywhere:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_API_URL
          valueFrom:
            configMapKeyRef:
              name: next-trip-config
              key: api-url
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: next-trip-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: next-trip-secrets
              key: redis-url
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: next-trip-secrets
              key: session-secret
        - name: NEXT_PUBLIC_SENTRY_DSN
          valueFrom:
            configMapKeyRef:
              name: next-trip-config
              key: sentry-dsn
        - name: NEXT_PUBLIC_GA_MEASUREMENT_ID
          valueFrom:
            configMapKeyRef:
              name: next-trip-config
              key: ga-measurement-id
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
            httpHeaders:
            - name: User-Agent
              value: Kubernetes-Health-Check
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/ready
            port: 3000
            httpHeaders:
            - name: User-Agent
              value: Kubernetes-Health-Check
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
        volumeMounts:
        - name: cache
          mountPath: /app/.next/cache
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
      volumes:
      - name: cache
        emptyDir:
          sizeLimit: 1Gi
      imagePullSecrets:
      - name: ghcr-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: next-trip-service
  namespace: production
  labels:
    app: next-trip
    environment: production
spec:
  type: ClusterIP
  selector:
    app: next-trip
    environment: production
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: next-trip-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: next-trip-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: next-trip-pdb
  namespace: production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: next-trip
      environment: production